#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pry-byebug'

require_relative '../lib/jack_compiler'

path = ARGV[0].to_s

ast = Nokogiri::XML(File.read(path))
ast_parser = JackCompiler::TreeParser.new

node_name = ast.document.root
statement_node = ast_parser.statement_node(node_name)

puts ast.document.root
