#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pry-byebug'

require_relative '../lib/jack_compiler'

# def put_vm_code()
#   binding.pry if node.name == JackCompiler::Statement::IF_STATEMENT
#
#   node.children.each do |item|
#     find_if_node(item)
#   end
# end

path = ARGV[0].to_s

ast = Nokogiri::XML(File.read(path))
ast_parser = JackCompiler::TreeParser.new

root = ast.document.root
ast_parser.put_vm_code(root)
#
# # statement_node = ast_parser.statement_node(root)
# find_if_node(root)
#
# puts root
