#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pry-byebug'

require_relative '../lib/jack_compiler'

path = ARGV[0].to_s

state_machine = JackCompiler::StateMachine.new(path)

puts state_machine.statements
state_machine.parse
# binding.pry

puts document.to_xml
