#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/vm_translator'

path = ARGV[0].to_s
initialize = ARGV[1] == 'true'

def glob?(path)
  path.include? '*'
end

def read_klazzes(path)
  paths = Dir.glob path

  paths.map do |item|
    VMTranslator::Klazz.initialize_from_file(item)
  end
end

begin
  klazzes = read_klazzes(path)

  parser = VMTranslator::Parser.new(klazzes)

  parser.initialize_stack_machine

  parser.parse(init: initialize)
  parser.put_end_program
rescue StandardError => e
  puts "Error converting VM to ASM: #{e}"
  puts e.backtrace

  exit 1
end

exit 0
