#!/usr/bin/env ruby
# frozen_string_literal: true

test_file = ARGV[0].to_s
initialize = ARGV[1] == 'true'

begin
  puts "Testing\t#{test_file}"

  directory = File.dirname test_file
  vm_files_glob = File.join(directory, '*.vm')
  test_extension = File.extname test_file
  actual_asm_file = test_file.gsub(test_extension, '.asm')

  File.delete actual_asm_file if File.exist? actual_asm_file

  result = system("./exe/compiler '#{vm_files_glob}' #{initialize} >> #{actual_asm_file}")
  raise "Failed to compile #{vm_files_glob}" unless result

  result = system("../nand2tetris/tools/CPUEmulator.sh #{test_file}")
  raise "Test failed: #{test_file}" unless result
rescue StandardError => e
  puts e

  exit 1
end

exit 0
