# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in jack_compiler.gemspec
gemspec

gem 'activesupport', '~> 7.2.2'
gem 'nokogiri', '~> 1.18.2'
gem 'pry', '~> 0.15.2'
gem 'rake', '~> 13.2'
gem 'rubocop', '~> 1.71'
